steps:
- name: 'gcr.io/$PROJECT_ID/graalvm-builder'
  id: Build:Java
  args: ['mvn', 'package', '-Pnative']
- name: 'gcr.io/cloud-builders/docker'
  id: Build:Image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/example-gcp-graal', '-f', 'src/main/docker/Dockerfile.native-distroless', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Ship:Push
  args: ['push', 'gcr.io/$PROJECT_ID/example-gcp-graal']
- name: 'gcr.io/cloud-builders/gcloud'
  id: Ship:Deploy
  args: ['run', 'deploy', 'example-gcp-graal', 
  '--image', 'gcr.io/$PROJECT_ID/example-gcp-graal', 
  '--region', 'us-central1', 
  '--platform', 'managed', 
  '--allow-unauthenticated',
  '--service-account', '${_SRV_ACC}'
  ]
images:
- gcr.io/$PROJECT_ID/example-gcp-graal
options:
 machineType: 'E2_HIGHCPU_8'